#************************Makefile***************************
#Program: temperature-rpi
#Compiler: GCC
#Author: Jesimar da Silva Arantes
#Date: 11/09/2018
#Last Update: 11/09/2018
#Description: Compilation of program temperature-rpi
#***********************************************************

all: 
	gcc -Wall -o temperature-rpi temperature-rpi.c -lwiringPi

clean:
	rm -rf *.o
