############################# Makefile ##########################
#Author: Jesimar da Silva Arantes
#Date: 11/09/2018

all: 
	gcc -Wall -o temperature-rpi temperature-rpi.c -lwiringPi

clean:
	rm -rf *.o
