package uav.gcs.planner;

import java.io.File;
import java.io.FileNotFoundException;
import java.io.PrintStream;
import java.util.Scanner;
import lib.color.StandardPrints;
import lib.uav.struct.Waypoint;
import lib.uav.struct.geom.PointGeo;
import lib.uav.struct.geom.Position3D;
import lib.uav.util.UtilGeo;
import lib.uav.util.UtilIO;
import uav.gcs.struct.Drone;

/**
 * The class models the generic path planner, called GPathPlanner4m.
 * @author Jesimar S. Arantes
 * @since version 4.0.0
 * @see Planner
 */
public class GPathPlanner4m extends Planner{
    
    /**
     * Class constructor - Used in G-Path-Planner
     * @param drone instance of the aircraft
     * @param dirFiles directory of main files 
     * @param fileGeoBase name of file geoBase
     * @param dirPlanner planner directory
     * @param cmdExecPlanner command to exec the planner
     * @param altitudeFlight flight altitude cruising
     * @since version 4.0.0
     */
    public GPathPlanner4m(Drone drone, String dirFiles, String fileGeoBase, 
            String dirPlanner, String cmdExecPlanner, String altitudeFlight) {
        super(drone, dirFiles, fileGeoBase, dirPlanner, 
                cmdExecPlanner, altitudeFlight);
    }
    
    /**
     * Execute the mission
     * @return {@code true} if the execution was successful
     *         {@code false} otherwise
     * @since version 4.0.0
     */
    public boolean execMission() {    
        boolean itIsOkExec   = execMethod();
        boolean itIsOkCopy   = copyRoute3D();
        boolean itIsOkParse  = parseRoute3DtoGeo();
        return itIsOkExec && itIsOkCopy && itIsOkParse;
    }
    
    /**
     * Copy the route file
     * @return {@code true} if the execution was successful
     *         {@code false} otherwise
     * @since version 4.0.0
     */
    public boolean copyRoute3D(){
        try {
            File fileRoute3D = new File(dir + "route3D.txt");
            PrintStream print3D = new PrintStream(fileRoute3D);
            Scanner readRoute3D = new Scanner(new File(dir + "output.txt"));
            double h = Double.parseDouble(altitudeFlight);
            while(readRoute3D.hasNext()){
                double x = readRoute3D.nextDouble();
                double y = readRoute3D.nextDouble();
                print3D.println(x + ";" + y + ";" + h);
            }
            readRoute3D.close();
            print3D.close();
            return true;
        } catch (FileNotFoundException ex) {
            StandardPrints.printMsgWarning("Warning [FileNotFoundException] copyRoute3D()");
            ex.printStackTrace();
            return false;
        } 
    }
    
    /**
     * Converts the route in Cartesian coordinates to geographic coordinates 
     * @return {@code true} if the execution was successful, 
     *         {@code false} otherwise
     * @since version 4.0.0
     */
    public boolean parseRoute3DtoGeo(){
        try {
            String nameFileRoute3D =  "output.txt";
            String nameFileRouteGeo = "routeGeo.txt";
            PointGeo pGeoBase = UtilGeo.getPointGeoBase(dirFiles + fileGeoBase);
            File fileRouteGeo = new File(dir + nameFileRouteGeo);
            PrintStream printGeo = new PrintStream(fileRouteGeo);
            Scanner readRoute3D = new Scanner(new File(dir + nameFileRoute3D));
            int countLines = 0;
            double h = Double.parseDouble(altitudeFlight);            
            while(readRoute3D.hasNext()){
                double x = readRoute3D.nextDouble();
                double y = readRoute3D.nextDouble();
                printGeo.println(UtilGeo.parseToGeo(pGeoBase, x, y, h, ";"));
                mission3D.addPosition(new Position3D(x, y, h));
                missionGeo.addWaypoint(new Waypoint(UtilGeo.parseToGeo1(pGeoBase, x, y, h)));
                countLines++;
            }
            if (countLines == 0){
                StandardPrints.printMsgWarning("Route-Empty");
                if (!drone.statusUAV.armed){
                    System.exit(1);
                }
            }
            readRoute3D.close();
            printGeo.close();
            return true;
        } catch (FileNotFoundException ex) {
            StandardPrints.printMsgWarning("Warning [FileNotFoundException] parseRoute3DtoGeo()");
            ex.printStackTrace();
            return false;
        } 
    }
    
    /**
     * Clears log files generated by method
     * @since version 4.0.0
     */
    @Override
    public void clearLogs() {
        UtilIO.deleteFile(new File(dir), ".log");
        UtilIO.deleteFile(new File(dir), ".png");
        UtilIO.deleteFile(new File(dir), ".err");
    }

}
