#************************Makefile***************************
#Program: UAV-Routes-Standard
#Compiler: GCC
#Author: Jesimar da Silva Arantes
#Date: 08/06/2016
#Last Update: 05/02/2018
#Description: Program to generate routes with standard formats for the UAV.
#Descrição: Programa para gerar rotas com formatos padrões para o VANT.
#***********************************************************

all: uav_routes_standard

uav_routes_standard: uav-routes-standard.c
	gcc uav-routes-standard.c -o uav_routes_standard -lm

clean:
	rm -rf *.o uav_routes_standard
